# coding: utf-8

"""
    Gitea API.

    This documentation describes the Gitea API.  # noqa: E501

    OpenAPI spec version: 1.18.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import gitea_api
from gitea_api.models.create_file_options import CreateFileOptions  # noqa: E501
from gitea_api.rest import ApiException


class TestCreateFileOptions(unittest.TestCase):
    """CreateFileOptions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateFileOptions(self):
        """Test CreateFileOptions"""
        # FIXME: construct object with mandatory attributes with example values
        # model = gitea_api.models.create_file_options.CreateFileOptions()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
