# coding: utf-8

"""
    Gitea API.

    This documentation describes the Gitea API.  # noqa: E501

    OpenAPI spec version: 1.17.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import gitea_api
from gitea_api.models.issue_labels_option import IssueLabelsOption  # noqa: E501
from gitea_api.rest import ApiException


class TestIssueLabelsOption(unittest.TestCase):
    """IssueLabelsOption unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIssueLabelsOption(self):
        """Test IssueLabelsOption"""
        # FIXME: construct object with mandatory attributes with example values
        # model = gitea_api.models.issue_labels_option.IssueLabelsOption()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
