# coding: utf-8

"""
    Gitea API.

    This documentation describes the Gitea API.  # noqa: E501

    OpenAPI spec version: 1.18.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import gitea_api
from gitea_api.models.payload_commit import PayloadCommit  # noqa: E501
from gitea_api.rest import ApiException


class TestPayloadCommit(unittest.TestCase):
    """PayloadCommit unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPayloadCommit(self):
        """Test PayloadCommit"""
        # FIXME: construct object with mandatory attributes with example values
        # model = gitea_api.models.payload_commit.PayloadCommit()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
