# coding: utf-8

"""
    Gitea API.

    This documentation describes the Gitea API.  # noqa: E501

    OpenAPI spec version: 1.17.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import gitea_api
from gitea_api.models.edit_milestone_option import EditMilestoneOption  # noqa: E501
from gitea_api.rest import ApiException


class TestEditMilestoneOption(unittest.TestCase):
    """EditMilestoneOption unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEditMilestoneOption(self):
        """Test EditMilestoneOption"""
        # FIXME: construct object with mandatory attributes with example values
        # model = gitea_api.models.edit_milestone_option.EditMilestoneOption()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
