# coding: utf-8

"""
    Gitea API.

    This documentation describes the Gitea API.  # noqa: E501

    OpenAPI spec version: 1.18.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import gitea_api
from gitea_api.models.state_type import StateType  # noqa: E501
from gitea_api.rest import ApiException


class TestStateType(unittest.TestCase):
    """StateType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStateType(self):
        """Test StateType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = gitea_api.models.state_type.StateType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
